"""
Product claim model for generated marketing copy with verification status.

Each claim is generated by the LLM orchestrator and anchored to a source
document. Claims flow through verification: pending_review → verified/flagged/rejected.
"""

import enum
from datetime import datetime

from sqlalchemy import (
    DateTime,
    Enum,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class ClaimStatus(str, enum.Enum):
    """Verification status for generated product claims."""

    PENDING_REVIEW = "pending_review"
    VERIFIED = "verified"
    FLAGGED = "flagged"
    REJECTED = "rejected"


class ProductClaim(Base):
    """A marketing claim generated for a product, with source anchoring."""

    __tablename__ = "product_claims"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    product_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("products.id"), nullable=False
    )
    claim_text: Mapped[str] = mapped_column(Text, nullable=False)
    source_doc_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("product_documents.id"), default=None
    )
    status: Mapped[ClaimStatus] = mapped_column(
        Enum(ClaimStatus, create_constraint=True),
        default=ClaimStatus.PENDING_REVIEW,
        nullable=False,
    )
    assigned_to: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("users.id"), default=None
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # ── Relationships ──────────────────────────────────────────────────
    product: Mapped["Product"] = relationship(
        "Product", back_populates="claims"
    )
    source_doc: Mapped["ProductDocument | None"] = relationship(
        "ProductDocument",
        foreign_keys=[source_doc_id],
        back_populates="claims",
    )
    assignee: Mapped["User | None"] = relationship(
        "User", foreign_keys=[assigned_to], back_populates="documents_assigned"
    )
